import { NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { Category, QualityGrade, ListingStatus, UserRole, OrderStatus, PaymentStatus, TerrainType, DeliveryStatus } from '@prisma/client';

// POST /api/seed - Seed database with sample data
export async function POST() {
  try {
    // Clear existing data
    await db.trackingEvent.deleteMany();
    await db.delivery.deleteMany();
    await db.cartItem.deleteMany();
    await db.order.deleteMany();
    await db.review.deleteMany();
    await db.listing.deleteMany();
    await db.notification.deleteMany();
    await db.user.deleteMany();

    // Create Users (with mock clerkIds for demo)
    const users = await Promise.all([
      db.user.create({
        data: {
          clerkId: 'demo_farmer_1',
          email: 'rahul.sharma@email.com',
          name: 'Rahul Sharma',
          phone: '+91 98765 43210',
          role: UserRole.FARMER,
          businessName: 'Jampui Hills Organic Farm',
          description: 'Third generation farmer specializing in organic ginger and spices from the pristine hills of Tripura.',
          district: 'West Tripura',
          state: 'Tripura',
          address: 'Jampui Hills, West Tripura',
          pincode: '799102',
          isVerified: true,
          totalSales: 45,
          rating: 4.8,
          reviewCount: 23,
        },
      }),
      db.user.create({
        data: {
          clerkId: 'demo_farmer_2',
          email: 'limasen.ao@email.com',
          name: 'Limasen Ao',
          phone: '+91 87654 32109',
          role: UserRole.FARMER,
          businessName: 'Nagaland Highland Produce',
          description: 'Indigenous farmer from Mokokchung growing exotic fruits and king chilli.',
          district: 'Mokokchung',
          state: 'Nagaland',
          address: 'Chuchuyimpang, Mokokchung',
          pincode: '798601',
          isVerified: true,
          totalSales: 32,
          rating: 4.6,
          reviewCount: 15,
        },
      }),
      db.user.create({
        data: {
          clerkId: 'demo_farmer_3',
          email: 'tashi.dorjee@email.com',
          name: 'Tashi Dorjee',
          phone: '+91 76543 21098',
          role: UserRole.FARMER,
          businessName: 'Sikkim Mountain Organics',
          description: 'Organic farmer from Sikkim specializing in large cardamom and honey.',
          district: 'East Sikkim',
          state: 'Sikkim',
          address: 'Gangtok, East Sikkim',
          pincode: '737101',
          isVerified: true,
          totalSales: 28,
          rating: 4.9,
          reviewCount: 18,
        },
      }),
      db.user.create({
        data: {
          clerkId: 'demo_farmer_4',
          email: 'priya.devi@email.com',
          name: 'Priya Devi',
          phone: '+91 65432 10987',
          role: UserRole.FARMER,
          businessName: 'Manipur Black Rice Collective',
          description: 'Traditional rice farmer preserving the heritage of Chakhao black rice.',
          district: 'Imphal West',
          state: 'Manipur',
          address: 'Langthabal, Imphal West',
          pincode: '795004',
          isVerified: true,
          totalSales: 56,
          rating: 4.7,
          reviewCount: 31,
        },
      }),
      db.user.create({
        data: {
          clerkId: 'demo_farmer_5',
          email: 'bapuk.das@email.com',
          name: 'Bapuk Das',
          phone: '+91 54321 09876',
          role: UserRole.FARMER,
          businessName: 'Assam Tea & Spices Estate',
          description: 'Multi-generational farmer with tea gardens and spice plantations in Upper Assam.',
          district: 'Dibrugarh',
          state: 'Assam',
          address: 'Naharkatia, Dibrugarh',
          pincode: '786004',
          isVerified: true,
          totalSales: 89,
          rating: 4.5,
          reviewCount: 42,
        },
      }),
      db.user.create({
        data: {
          clerkId: 'demo_farmer_6',
          email: 'john.meghalaya@email.com',
          name: 'John Marwein',
          phone: '+91 43210 98765',
          role: UserRole.FARMER,
          businessName: 'Meghalaya Exotic Produce',
          description: 'Farmer from the wettest place on earth, specializing in rare herbs and organic vegetables.',
          district: 'East Khasi Hills',
          state: 'Meghalaya',
          address: 'Cherrapunji, East Khasi Hills',
          pincode: '793108',
          isVerified: true,
          totalSales: 34,
          rating: 4.8,
          reviewCount: 16,
        },
      }),
      db.user.create({
        data: {
          clerkId: 'demo_buyer',
          email: 'buyer@email.com',
          name: 'Amit Kumar',
          phone: '+91 12345 67890',
          role: UserRole.BUYER,
          district: 'Kamrup Metropolitan',
          state: 'Assam',
          address: 'GS Road, Guwahati, Assam',
          pincode: '781005',
          isVerified: true,
          totalPurchases: 15,
        },
      }),
      db.user.create({
        data: {
          clerkId: 'demo_rider',
          email: 'rider@email.com',
          name: 'Rajesh Singh',
          phone: '+91 11111 22222',
          role: UserRole.LOGISTICS,
          district: 'Kamrup Metropolitan',
          state: 'Assam',
          address: 'Guwahati, Assam',
          pincode: '781001',
          isVerified: true,
        },
      }),
    ]);

    // Create Listings
    const listings = await Promise.all([
      db.listing.create({
        data: {
          title: 'Organic Ginger - Fresh from Jampui Hills',
          description: 'Premium quality organic ginger grown in the pristine hills of Jampui. Known for its intense flavor and medicinal properties. Harvested using traditional methods without any chemicals or pesticides. Perfect for culinary use and traditional medicine. Minimum order 5kg, bulk discounts available.',
          category: Category.SPICES,
          price: 180,
          unit: 'kg',
          minOrder: 5,
          maxQuantity: 500,
          quality: QualityGrade.A_PLUS,
          isOrganic: true,
          isVerified: true,
          district: 'West Tripura',
          state: 'Tripura',
          harvestDate: new Date('2024-12-01'),
          viewCount: 245,
          orderCount: 18,
          status: ListingStatus.ACTIVE,
          sellerId: users[0].id,
        },
      }),
      db.listing.create({
        data: {
          title: 'Nagaland Kiwi - Premium Quality',
          description: 'Fresh kiwi from the high-altitude farms of Nagaland. Sweet, tangy, and packed with nutrients. Perfect for snacking or making juices. Limited seasonal harvest from December to February. Grown at altitudes above 1500m for optimal sweetness.',
          category: Category.FRUITS,
          price: 320,
          unit: 'kg',
          minOrder: 2,
          maxQuantity: 100,
          quality: QualityGrade.A_PLUS,
          isOrganic: true,
          isVerified: true,
          district: 'Mokokchung',
          state: 'Nagaland',
          harvestDate: new Date('2024-11-20'),
          viewCount: 189,
          orderCount: 12,
          status: ListingStatus.ACTIVE,
          sellerId: users[1].id,
        },
      }),
      db.listing.create({
        data: {
          title: 'Sikkim Large Cardamom (Bari Elaichi)',
          description: 'World-renowned large cardamom from Sikkim. Known for its distinct smoky flavor and aroma. Essential ingredient in Indian cuisine and traditional medicine. Harvested from 1000m+ altitude farms. Used in chai, biryani, and ayurvedic preparations.',
          category: Category.SPICES,
          price: 850,
          unit: 'kg',
          minOrder: 1,
          maxQuantity: 50,
          quality: QualityGrade.A_PLUS,
          isOrganic: true,
          isVerified: true,
          district: 'East Sikkim',
          state: 'Sikkim',
          harvestDate: new Date('2024-10-15'),
          viewCount: 312,
          orderCount: 25,
          status: ListingStatus.ACTIVE,
          sellerId: users[2].id,
        },
      }),
      db.listing.create({
        data: {
          title: 'Manipur Black Rice (Chakhao)',
          description: 'Traditional black rice from Manipur, locally known as Chakhao. Rich in antioxidants and has a unique nutty flavor. Perfect for desserts and special occasions. GI tagged product with deep cultural significance. Turns purple when cooked.',
          category: Category.GRAINS,
          price: 250,
          unit: 'kg',
          minOrder: 5,
          maxQuantity: 200,
          quality: QualityGrade.A_PLUS,
          isOrganic: true,
          isVerified: true,
          district: 'Imphal West',
          state: 'Manipur',
          harvestDate: new Date('2024-11-10'),
          viewCount: 423,
          orderCount: 34,
          status: ListingStatus.ACTIVE,
          sellerId: users[3].id,
        },
      }),
      db.listing.create({
        data: {
          title: 'Fresh Turmeric - Lakadong Variety',
          description: 'High curcumin content turmeric from the Lakadong region. Known for its exceptional medicinal properties and vibrant color. Curcumin content of 7-12%, highest in the world. Perfect for health conscious consumers and ayurvedic practitioners.',
          category: Category.SPICES,
          price: 220,
          unit: 'kg',
          minOrder: 5,
          maxQuantity: 300,
          quality: QualityGrade.A_PLUS,
          isOrganic: true,
          isVerified: true,
          district: 'Dibrugarh',
          state: 'Assam',
          harvestDate: new Date('2024-12-10'),
          viewCount: 567,
          orderCount: 45,
          status: ListingStatus.ACTIVE,
          sellerId: users[4].id,
        },
      }),
      db.listing.create({
        data: {
          title: 'Fresh Bamboo Shoots - Assam Special',
          description: 'Tender bamboo shoots harvested from the forests of Assam. A staple ingredient in Northeast Indian cuisine. Perfect for traditional dishes like bamboo shoot pickle, fish curry, and pork dishes. Harvested fresh and available during season.',
          category: Category.VEGETABLES,
          price: 80,
          unit: 'kg',
          minOrder: 10,
          maxQuantity: 1000,
          quality: QualityGrade.A,
          isOrganic: true,
          isVerified: false,
          district: 'Dibrugarh',
          state: 'Assam',
          harvestDate: new Date('2024-12-20'),
          viewCount: 156,
          orderCount: 8,
          status: ListingStatus.ACTIVE,
          sellerId: users[4].id,
        },
      }),
      db.listing.create({
        data: {
          title: 'Arunachal Organic Honey',
          description: 'Pure raw honey from the pristine forests of Arunachal Pradesh. Collected using sustainable practices by indigenous communities. Unprocessed and unheated to retain all natural enzymes and nutrients. Rich forest flora gives unique taste.',
          category: Category.HONEY,
          price: 650,
          unit: 'kg',
          minOrder: 1,
          maxQuantity: 20,
          quality: QualityGrade.A_PLUS,
          isOrganic: true,
          isVerified: true,
          district: 'West Kameng',
          state: 'Arunachal Pradesh',
          harvestDate: new Date('2024-11-01'),
          viewCount: 234,
          orderCount: 19,
          status: ListingStatus.ACTIVE,
          sellerId: users[2].id,
        },
      }),
      db.listing.create({
        data: {
          title: 'Assam Orthodox Tea - Premium Grade',
          description: 'Single-origin orthodox tea from the tea gardens of Assam. Full-bodied, malty flavor with bright liquor. Hand-plucked and traditionally processed. Perfect for morning tea. Second flush for the best flavor.',
          category: Category.TEA,
          price: 450,
          unit: 'kg',
          minOrder: 2,
          maxQuantity: 100,
          quality: QualityGrade.A_PLUS,
          isOrganic: false,
          isVerified: true,
          district: 'Dibrugarh',
          state: 'Assam',
          harvestDate: new Date('2024-12-01'),
          viewCount: 345,
          orderCount: 28,
          status: ListingStatus.ACTIVE,
          sellerId: users[4].id,
        },
      }),
      db.listing.create({
        data: {
          title: 'King Chilli (Bhut Jolokia) - Dried',
          description: 'World-famous King Chilli from Nagaland. Once the hottest chilli in the world with over 1 million Scoville units. Essential for authentic Northeast cuisine. Dried for longer shelf life. Use with caution!',
          category: Category.SPICES,
          price: 1200,
          unit: 'kg',
          minOrder: 0.5,
          maxQuantity: 20,
          quality: QualityGrade.A_PLUS,
          isOrganic: true,
          isVerified: true,
          district: 'Kohima',
          state: 'Nagaland',
          harvestDate: new Date('2024-10-20'),
          viewCount: 456,
          orderCount: 32,
          status: ListingStatus.ACTIVE,
          sellerId: users[1].id,
        },
      }),
      db.listing.create({
        data: {
          title: 'Meghalaya Sohphie (Wild Mangosteen)',
          description: 'Rare wild mangosteen from the forests of Meghalaya. Sweet and tangy with a unique flavor. Available only during short season. Rich in vitamins and antioxidants. A delicacy from the wettest place on earth.',
          category: Category.FRUITS,
          price: 400,
          unit: 'kg',
          minOrder: 2,
          maxQuantity: 50,
          quality: QualityGrade.A_PLUS,
          isOrganic: true,
          isVerified: true,
          district: 'East Khasi Hills',
          state: 'Meghalaya',
          harvestDate: new Date('2024-12-15'),
          viewCount: 189,
          orderCount: 14,
          status: ListingStatus.ACTIVE,
          sellerId: users[5].id,
        },
      }),
      db.listing.create({
        data: {
          title: 'Organic Lemongrass - Fresh',
          description: 'Aromatic lemongrass from the organic farms of Meghalaya. Perfect for tea, cooking, and essential oil extraction. Grown without pesticides in pristine mountain environment.',
          category: Category.HERBS,
          price: 150,
          unit: 'kg',
          minOrder: 5,
          maxQuantity: 200,
          quality: QualityGrade.A,
          isOrganic: true,
          isVerified: true,
          district: 'East Khasi Hills',
          state: 'Meghalaya',
          harvestDate: new Date('2024-12-18'),
          viewCount: 98,
          orderCount: 7,
          status: ListingStatus.ACTIVE,
          sellerId: users[5].id,
        },
      }),
      db.listing.create({
        data: {
          title: 'Mizoram Bird Eye Chilli',
          description: 'Small but extremely spicy bird eye chilli from Mizoram. Popular in Southeast Asian cuisine. Grown in the hills using traditional methods. Perfect for hot sauces and spicy dishes.',
          category: Category.SPICES,
          price: 600,
          unit: 'kg',
          minOrder: 2,
          maxQuantity: 100,
          quality: QualityGrade.A,
          isOrganic: true,
          isVerified: false,
          district: 'Aizawl',
          state: 'Mizoram',
          harvestDate: new Date('2024-11-25'),
          viewCount: 167,
          orderCount: 11,
          status: ListingStatus.ACTIVE,
          sellerId: users[1].id,
        },
      }),
    ]);

    // Create sample orders
    const order1 = await db.order.create({
      data: {
        buyerId: users[6].id,
        sellerId: users[0].id,
        listingId: listings[0].id,
        quantity: 25,
        unitPrice: 180,
        totalPrice: 4500,
        status: OrderStatus.DELIVERED,
        paymentStatus: PaymentStatus.PAID,
        paymentMethod: 'UPI',
        deliveryAddress: '123 Market Street, GS Road',
        deliveryDistrict: 'Kamrup Metropolitan',
        deliveryState: 'Assam',
        deliveryPincode: '781005',
        deliveryPhone: '+91 12345 67890',
      },
    });

    const order2 = await db.order.create({
      data: {
        buyerId: users[6].id,
        sellerId: users[2].id,
        listingId: listings[2].id,
        quantity: 2,
        unitPrice: 850,
        totalPrice: 1700,
        status: OrderStatus.IN_TRANSIT,
        paymentStatus: PaymentStatus.PAID,
        paymentMethod: 'Card',
        deliveryAddress: '123 Market Street, GS Road',
        deliveryDistrict: 'Kamrup Metropolitan',
        deliveryState: 'Assam',
        deliveryPincode: '781005',
        deliveryPhone: '+91 12345 67890',
      },
    });

    const order3 = await db.order.create({
      data: {
        buyerId: users[6].id,
        sellerId: users[3].id,
        listingId: listings[3].id,
        quantity: 10,
        unitPrice: 250,
        totalPrice: 2500,
        status: OrderStatus.PENDING,
        paymentStatus: PaymentStatus.PENDING,
        deliveryAddress: '123 Market Street, GS Road',
        deliveryDistrict: 'Kamrup Metropolitan',
        deliveryState: 'Assam',
        deliveryPincode: '781005',
        deliveryPhone: '+91 12345 67890',
      },
    });

    // Create tracking events
    await db.trackingEvent.createMany({
      data: [
        { orderId: order1.id, status: 'PENDING', description: 'Order placed', timestamp: new Date('2024-12-10T10:00:00Z') },
        { orderId: order1.id, status: 'CONFIRMED', description: 'Order confirmed by seller', timestamp: new Date('2024-12-10T11:30:00Z') },
        { orderId: order1.id, status: 'SHIPPED', description: 'Shipped from Jampui Hills', location: 'West Tripura', timestamp: new Date('2024-12-11T09:00:00Z') },
        { orderId: order1.id, status: 'IN_TRANSIT', description: 'In transit to Guwahati', location: 'National Highway 8', timestamp: new Date('2024-12-12T08:00:00Z') },
        { orderId: order1.id, status: 'DELIVERED', description: 'Delivered successfully', location: 'Guwahati', timestamp: new Date('2024-12-13T14:30:00Z') },
        { orderId: order2.id, status: 'PENDING', description: 'Order placed', timestamp: new Date('2024-12-20T10:00:00Z') },
        { orderId: order2.id, status: 'CONFIRMED', description: 'Order confirmed by seller', timestamp: new Date('2024-12-20T14:00:00Z') },
        { orderId: order2.id, status: 'SHIPPED', description: 'Shipped from Gangtok', location: 'East Sikkim', timestamp: new Date('2024-12-21T08:00:00Z') },
        { orderId: order2.id, status: 'IN_TRANSIT', description: 'Package in transit', location: 'Siliguri Junction', timestamp: new Date('2024-12-21T18:00:00Z') },
      ],
    });

    // Create delivery
    await db.delivery.create({
      data: {
        orderId: order1.id,
        riderId: users[7].id,
        pickupLocation: 'Jampui Hills, West Tripura',
        dropLocation: 'Guwahati, Assam',
        estimatedDistance: 180,
        estimatedTime: 180,
        terrainType: TerrainType.HILLY,
        difficultyLevel: 3,
        status: DeliveryStatus.DELIVERED,
        baseFare: 350,
        terrainBonus: 100,
        totalEarnings: 450,
      },
    });

    // Create reviews
    await db.review.createMany({
      data: [
        {
          listingId: listings[0].id,
          reviewerId: users[6].id,
          rating: 5,
          comment: 'Excellent quality ginger! Very fresh and aromatic. Will order again.',
          isVerified: true,
        },
        {
          listingId: listings[2].id,
          reviewerId: users[6].id,
          rating: 4,
          comment: 'Great cardamom, authentic Sikkim variety. Packaging could be better.',
          isVerified: true,
        },
      ],
    });

    // Create notifications
    await db.notification.createMany({
      data: [
        {
          userId: users[6].id,
          type: 'ORDER_DELIVERED',
          title: 'Order Delivered',
          message: 'Your order #ORD001 has been delivered successfully',
          isRead: true,
        },
        {
          userId: users[6].id,
          type: 'ORDER_SHIPPED',
          title: 'Order Shipped',
          message: 'Your order #ORD002 is on its way',
          isRead: false,
        },
        {
          userId: users[6].id,
          type: 'ORDER_PLACED',
          title: 'Order Confirmed',
          message: 'Your order #ORD003 has been placed successfully',
          isRead: false,
        },
      ],
    });

    return NextResponse.json({
      success: true,
      message: 'Database seeded successfully',
      data: {
        users: users.length,
        listings: listings.length,
        orders: 3,
        reviews: 2,
      },
    });
  } catch (error) {
    console.error('Error seeding database:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to seed database' },
      { status: 500 }
    );
  }
}
